### ISSUE TITLE
mobile touch support

### ISSUE THREAD

**Issue by darkworks** [GSRHackZ/Auto-Cicker-For-Browsers#1]
cool nice script , can u please add mobile touch support so that when in browser from console option when device view is enabled then click will not work only touch event.

**Comment by GSRHackZ** [comment]
# #

**Comment by GSRHackZ** [comment]
I tried it on chrome and it was working. What browser are you using?

**Comment by darkworks** [comment]
> I tried it on chrome and it was working. What browser are you using?

chrome , can u test it on : https://sale.aliexpress.com/__mobile/coin_channel.htm  , try to click on [ water ] button
